# Usa a imagem oficial do Nginx
FROM nginx:latest

# Remove o arquivo de configuração padrão, se necessário
RUN rm /etc/nginx/conf.d/default.conf

# Copia seu arquivo de configuração personalizado para o container
COPY default.conf /etc/nginx/conf.d/default.conf

# Expondo a porta 80
EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
